[microcloud]
# Liste de vos serveurs (remplacez les IPs par les adresses réelles de vos nœuds)
mc-node1 ansible_host=192.168.1.11
mc-node2 ansible_host=192.168.1.12
mc-node3 ansible_host=192.168.1.13

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_rsa
# Décommentez la ligne ci-dessous si vous utilisez un autre utilisateur que root nécessitant un mot de passe sudo
# ansible_become_pass=VotreMotDePasseSudo
