[microcloud]
# List of your servers (replace IPs with the real addresses of your nodes)
microcloud01 ansible_host=192.168.1.11
microcloud02 ansible_host=192.168.1.12
microcloud03 ansible_host=192.168.1.13

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_rsa
# Uncomment the line below if you are using a user other than root that requires a sudo password
# ansible_become_pass=YourSudoPassword
